apiVersion: argoproj.io/v1alpha1 
kind: Rollout
metadata:
  name: apache-ro
  namespace: apache-ns
spec:
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.55
  selector:
    matchLabels:
      app: apache
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}
