apiVersion: argoproj.io/v1alpha1  # the version of the Argo Rollouts API
kind: Rollout      #specifies the type of resource
metadata:
  name: apache-ro
  namespace: apache-ns
spec:
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.56
  selector:      # used to match the Pods that the Rollout is managing
    matchLabels:
      app: apache
  replicas: 4           #the desired number of replicas for the Rollout
  strategy:     #specifies the deployment strategy for the Rollout
    canary:
      steps:
      - setWeight: 25
      - pause: {}     #This allows time for observation and testing before continuing with the full deployment.
